//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Enumeration of the ADSB altimeter types
    /// </summary>
    /// <remarks>
    /// ADSB_ALTITUDE_TYPE
    /// </remarks>
    public enum AdsbAltitudeType
    {
        
        /// <summary>
        /// Altitude reported from a Baro source using QNH reference
        /// </summary>
        /// <remarks>
        /// ADSB_ALTITUDE_TYPE_PRESSURE_QNH
        /// </remarks>
        [Description("Altitude reported from a Baro source using QNH reference")]
        PressureQnh = 0,
        
        /// <summary>
        /// Altitude reported from a GNSS source
        /// </summary>
        /// <remarks>
        /// ADSB_ALTITUDE_TYPE_GEOMETRIC
        /// </remarks>
        [Description("Altitude reported from a GNSS source")]
        Geometric = 1,
    }
}
