//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Enumeration of battery types
    /// </summary>
    /// <remarks>
    /// MAV_BATTERY_TYPE
    /// </remarks>
    public enum BatteryType
    {
        
        /// <summary>
        /// Not specified.
        /// </summary>
        /// <remarks>
        /// MAV_BATTERY_TYPE_UNKNOWN
        /// </remarks>
        [Description("Not specified.")]
        Unknown = 0,
        
        /// <summary>
        /// Lithium polymer battery
        /// </summary>
        /// <remarks>
        /// MAV_BATTERY_TYPE_LIPO
        /// </remarks>
        [Description("Lithium polymer battery")]
        Lipo = 1,
        
        /// <summary>
        /// Lithium-iron-phosphate battery
        /// </summary>
        /// <remarks>
        /// MAV_BATTERY_TYPE_LIFE
        /// </remarks>
        [Description("Lithium-iron-phosphate battery")]
        Life = 2,
        
        /// <summary>
        /// Lithium-ION battery
        /// </summary>
        /// <remarks>
        /// MAV_BATTERY_TYPE_LION
        /// </remarks>
        [Description("Lithium-ION battery")]
        Lion = 3,
        
        /// <summary>
        /// Nickel metal hydride battery
        /// </summary>
        /// <remarks>
        /// MAV_BATTERY_TYPE_NIMH
        /// </remarks>
        [Description("Nickel metal hydride battery")]
        Nimh = 4,
    }
}
