//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// ACK / NACK / ERROR values as a result of MAV_CMDs and for mission item transmission.
    /// </summary>
    /// <remarks>
    /// MAV_CMD_ACK
    /// </remarks>
    public enum CmdAck
    {
        
        /// <summary>
        /// Command / mission item is ok.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_OK
        /// </remarks>
        [Description("Command / mission item is ok.")]
        Ok,
        
        /// <summary>
        /// Generic error message if none of the other reasons fails or if no detailed error reporting is implemented.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_FAIL
        /// </remarks>
        [Description("Generic error message if none of the other reasons fails or if no detailed error " +
            "reporting is implemented.")]
        ErrFail,
        
        /// <summary>
        /// The system is refusing to accept this command from this source / communication partner.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_ACCESS_DENIED
        /// </remarks>
        [Description("The system is refusing to accept this command from this source / communication pa" +
            "rtner.")]
        ErrAccessDenied,
        
        /// <summary>
        /// Command or mission item is not supported, other commands would be accepted.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_NOT_SUPPORTED
        /// </remarks>
        [Description("Command or mission item is not supported, other commands would be accepted.")]
        ErrNotSupported,
        
        /// <summary>
        /// The coordinate frame of this command / mission item is not supported.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_COORDINATE_FRAME_NOT_SUPPORTED
        /// </remarks>
        [Description("The coordinate frame of this command / mission item is not supported.")]
        ErrCoordinateFrameNotSupported,
        
        /// <summary>
        /// The coordinate frame of this command is ok, but he coordinate values exceed the safety limits of this system. This is a generic error, please use the more specific error messages below if possible.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_COORDINATES_OUT_OF_RANGE
        /// </remarks>
        [Description("The coordinate frame of this command is ok, but he coordinate values exceed the s" +
            "afety limits of this system. This is a generic error, please use the more specif" +
            "ic error messages below if possible.")]
        ErrCoordinatesOutOfRange,
        
        /// <summary>
        /// The X or latitude value is out of range.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_X_LAT_OUT_OF_RANGE
        /// </remarks>
        [Description("The X or latitude value is out of range.")]
        ErrXLatOutOfRange,
        
        /// <summary>
        /// The Y or longitude value is out of range.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_Y_LON_OUT_OF_RANGE
        /// </remarks>
        [Description("The Y or longitude value is out of range.")]
        ErrYLonOutOfRange,
        
        /// <summary>
        /// The Z or altitude value is out of range.
        /// </summary>
        /// <remarks>
        /// MAV_CMD_ACK_ERR_Z_ALT_OUT_OF_RANGE
        /// </remarks>
        [Description("The Z or altitude value is out of range.")]
        ErrZAltOutOfRange,
    }
}
