//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Aircraft-rated danger from this threat.
    /// </summary>
    /// <remarks>
    /// MAV_COLLISION_THREAT_LEVEL
    /// </remarks>
    public enum CollisionThreatLevel
    {
        
        /// <summary>
        /// Not a threat
        /// </summary>
        /// <remarks>
        /// MAV_COLLISION_THREAT_LEVEL_NONE
        /// </remarks>
        [Description("Not a threat")]
        None = 0,
        
        /// <summary>
        /// Craft is mildly concerned about this threat
        /// </summary>
        /// <remarks>
        /// MAV_COLLISION_THREAT_LEVEL_LOW
        /// </remarks>
        [Description("Craft is mildly concerned about this threat")]
        Low = 1,
        
        /// <summary>
        /// Craft is panicing, and may take actions to avoid threat
        /// </summary>
        /// <remarks>
        /// MAV_COLLISION_THREAT_LEVEL_HIGH
        /// </remarks>
        [Description("Craft is panicing, and may take actions to avoid threat")]
        High = 2,
    }
}
