//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Source of information about this collision.
    /// </summary>
    /// <remarks>
    /// MAV_COLLISION_SRC
    /// </remarks>
    public enum CollisionSrc
    {
        
        /// <summary>
        /// ID field references ADSB_VEHICLE packets
        /// </summary>
        /// <remarks>
        /// MAV_COLLISION_SRC_ADSB
        /// </remarks>
        [Description("ID field references ADSB_VEHICLE packets")]
        Adsb = 0,
        
        /// <summary>
        /// ID field references MAVLink SRC ID
        /// </summary>
        /// <remarks>
        /// MAV_COLLISION_SRC_MAVLINK_GPS_GLOBAL_INT
        /// </remarks>
        [Description("ID field references MAVLink SRC ID")]
        MavlinkGpsGlobalInt = 1,
    }
}
