//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Report status of a command. Includes feedback whether the command was executed.
    /// </summary>
    /// <remarks>
    /// COMMAND_ACK
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.CommandAck, Name="COMMAND_ACK", Description="Report status of a command. Includes feedback whether the command was executed.")]
    public class CommandAckMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Command ID, as defined by MAV_CMD enum.
        /// </summary>
        /// <remarks>
        /// command
        /// </remarks>
        private Cmd _command;
        
        /// <summary>
        /// See MAV_RESULT enum
        /// </summary>
        /// <remarks>
        /// result
        /// </remarks>
        private Result _result;
        
        public CommandAckMessage() : 
                base(MavLink4Net.Messages.MavMessageType.CommandAck, 143)
        {
        }
        
        /// <summary>
        /// Command ID, as defined by MAV_CMD enum.
        /// </summary>
        [MessageFieldMetadata(Name="command", Type="MAV_CMD enum", Description="Command ID, as defined by MAV_CMD enum.")]
        public Cmd Command
        {
            get
            {
                return this._command;
            }
            set
            {
                this._command = value;
            }
        }
        
        /// <summary>
        /// See MAV_RESULT enum
        /// </summary>
        [MessageFieldMetadata(Name="result", Type="MAV_RESULT enum", Description="See MAV_RESULT enum")]
        public Result Result
        {
            get
            {
                return this._result;
            }
            set
            {
                this._result = value;
            }
        }
    }
}
