//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// MAV_COMPONENT
    /// </remarks>
    public enum Component
    {
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_ALL
        /// </remarks>
        [Description(null)]
        All = 0,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_AUTOPILOT1
        /// </remarks>
        [Description(null)]
        Autopilot1 = 1,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA
        /// </remarks>
        [Description(null)]
        Camera = 100,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA2
        /// </remarks>
        [Description(null)]
        Camera2 = 101,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA3
        /// </remarks>
        [Description(null)]
        Camera3 = 102,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA4
        /// </remarks>
        [Description(null)]
        Camera4 = 103,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA5
        /// </remarks>
        [Description(null)]
        Camera5 = 104,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_CAMERA6
        /// </remarks>
        [Description(null)]
        Camera6 = 105,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO1
        /// </remarks>
        [Description(null)]
        Servo1 = 140,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO2
        /// </remarks>
        [Description(null)]
        Servo2 = 141,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO3
        /// </remarks>
        [Description(null)]
        Servo3 = 142,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO4
        /// </remarks>
        [Description(null)]
        Servo4 = 143,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO5
        /// </remarks>
        [Description(null)]
        Servo5 = 144,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO6
        /// </remarks>
        [Description(null)]
        Servo6 = 145,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO7
        /// </remarks>
        [Description(null)]
        Servo7 = 146,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO8
        /// </remarks>
        [Description(null)]
        Servo8 = 147,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO9
        /// </remarks>
        [Description(null)]
        Servo9 = 148,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO10
        /// </remarks>
        [Description(null)]
        Servo10 = 149,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO11
        /// </remarks>
        [Description(null)]
        Servo11 = 150,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO12
        /// </remarks>
        [Description(null)]
        Servo12 = 151,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO13
        /// </remarks>
        [Description(null)]
        Servo13 = 152,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SERVO14
        /// </remarks>
        [Description(null)]
        Servo14 = 153,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_GIMBAL
        /// </remarks>
        [Description(null)]
        Gimbal = 154,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_LOG
        /// </remarks>
        [Description(null)]
        Log = 155,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_ADSB
        /// </remarks>
        [Description(null)]
        Adsb = 156,
        
        /// <summary>
        /// On Screen Display (OSD) devices for video links
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_OSD
        /// </remarks>
        [Description("On Screen Display (OSD) devices for video links")]
        Osd = 157,
        
        /// <summary>
        /// Generic autopilot peripheral component ID. Meant for devices that do not implement the parameter sub-protocol
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_PERIPHERAL
        /// </remarks>
        [Description("Generic autopilot peripheral component ID. Meant for devices that do not implemen" +
            "t the parameter sub-protocol")]
        Peripheral = 158,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_QX1_GIMBAL
        /// </remarks>
        [Description(null)]
        Qx1Gimbal = 159,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_MAPPER
        /// </remarks>
        [Description(null)]
        Mapper = 180,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_MISSIONPLANNER
        /// </remarks>
        [Description(null)]
        Missionplanner = 190,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_PATHPLANNER
        /// </remarks>
        [Description(null)]
        Pathplanner = 195,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_IMU
        /// </remarks>
        [Description(null)]
        Imu = 200,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_IMU_2
        /// </remarks>
        [Description(null)]
        Imu2 = 201,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_IMU_3
        /// </remarks>
        [Description(null)]
        Imu3 = 202,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_GPS
        /// </remarks>
        [Description(null)]
        Gps = 220,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_GPS2
        /// </remarks>
        [Description(null)]
        Gps2 = 221,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_UDP_BRIDGE
        /// </remarks>
        [Description(null)]
        UdpBridge = 240,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_UART_BRIDGE
        /// </remarks>
        [Description(null)]
        UartBridge = 241,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAV_COMP_ID_SYSTEM_CONTROL
        /// </remarks>
        [Description(null)]
        SystemControl = 250,
    }
}
