//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Flags in EKF_STATUS message
    /// </summary>
    /// <remarks>
    /// ESTIMATOR_STATUS_FLAGS
    /// </remarks>
    public enum EstimatorStatusFlags
    {
        
        /// <summary>
        /// True if the attitude estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_ATTITUDE
        /// </remarks>
        [Description("True if the attitude estimate is good")]
        Attitude = 1,
        
        /// <summary>
        /// True if the horizontal velocity estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_VELOCITY_HORIZ
        /// </remarks>
        [Description("True if the horizontal velocity estimate is good")]
        VelocityHoriz = 2,
        
        /// <summary>
        /// True if the  vertical velocity estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_VELOCITY_VERT
        /// </remarks>
        [Description("True if the  vertical velocity estimate is good")]
        VelocityVert = 4,
        
        /// <summary>
        /// True if the horizontal position (relative) estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_POS_HORIZ_REL
        /// </remarks>
        [Description("True if the horizontal position (relative) estimate is good")]
        PosHorizRel = 8,
        
        /// <summary>
        /// True if the horizontal position (absolute) estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_POS_HORIZ_ABS
        /// </remarks>
        [Description("True if the horizontal position (absolute) estimate is good")]
        PosHorizAbs = 16,
        
        /// <summary>
        /// True if the vertical position (absolute) estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_POS_VERT_ABS
        /// </remarks>
        [Description("True if the vertical position (absolute) estimate is good")]
        PosVertAbs = 32,
        
        /// <summary>
        /// True if the vertical position (above ground) estimate is good
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_POS_VERT_AGL
        /// </remarks>
        [Description("True if the vertical position (above ground) estimate is good")]
        PosVertAgl = 64,
        
        /// <summary>
        /// True if the EKF is in a constant position mode and is not using external measurements (eg GPS or optical flow)
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_CONST_POS_MODE
        /// </remarks>
        [Description("True if the EKF is in a constant position mode and is not using external measurem" +
            "ents (eg GPS or optical flow)")]
        ConstPosMode = 128,
        
        /// <summary>
        /// True if the EKF has sufficient data to enter a mode that will provide a (relative) position estimate
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_PRED_POS_HORIZ_REL
        /// </remarks>
        [Description("True if the EKF has sufficient data to enter a mode that will provide a (relative" +
            ") position estimate")]
        PredPosHorizRel = 256,
        
        /// <summary>
        /// True if the EKF has sufficient data to enter a mode that will provide a (absolute) position estimate
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_PRED_POS_HORIZ_ABS
        /// </remarks>
        [Description("True if the EKF has sufficient data to enter a mode that will provide a (absolute" +
            ") position estimate")]
        PredPosHorizAbs = 512,
        
        /// <summary>
        /// True if the EKF has detected a GPS glitch
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_GPS_GLITCH
        /// </remarks>
        [Description("True if the EKF has detected a GPS glitch")]
        GpsGlitch = 1024,
        
        /// <summary>
        /// True if the EKF has detected bad accelerometer data
        /// </summary>
        /// <remarks>
        /// ESTIMATOR_ACCEL_ERROR
        /// </remarks>
        [Description("True if the EKF has detected bad accelerometer data")]
        AccelError = 2048,
    }
}
