//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Enumeration of estimator types
    /// </summary>
    /// <remarks>
    /// MAV_ESTIMATOR_TYPE
    /// </remarks>
    public enum EstimatorType
    {
        
        /// <summary>
        /// This is a naive estimator without any real covariance feedback.
        /// </summary>
        /// <remarks>
        /// MAV_ESTIMATOR_TYPE_NAIVE
        /// </remarks>
        [Description("This is a naive estimator without any real covariance feedback.")]
        Naive = 1,
        
        /// <summary>
        /// Computer vision based estimate. Might be up to scale.
        /// </summary>
        /// <remarks>
        /// MAV_ESTIMATOR_TYPE_VISION
        /// </remarks>
        [Description("Computer vision based estimate. Might be up to scale.")]
        Vision = 2,
        
        /// <summary>
        /// Visual-inertial estimate.
        /// </summary>
        /// <remarks>
        /// MAV_ESTIMATOR_TYPE_VIO
        /// </remarks>
        [Description("Visual-inertial estimate.")]
        Vio = 3,
        
        /// <summary>
        /// Plain GPS estimate.
        /// </summary>
        /// <remarks>
        /// MAV_ESTIMATOR_TYPE_GPS
        /// </remarks>
        [Description("Plain GPS estimate.")]
        Gps = 4,
        
        /// <summary>
        /// Estimator integrating GPS and inertial sensing.
        /// </summary>
        /// <remarks>
        /// MAV_ESTIMATOR_TYPE_GPS_INS
        /// </remarks>
        [Description("Estimator integrating GPS and inertial sensing.")]
        GpsIns = 5,
    }
}
