//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// The heartbeat message shows that a system is present and responding. The type of the MAV and Autopilot hardware allow the receiving system to treat further messages from this system appropriate (e.g. by laying out the user interface based on the autopilot).
    /// </summary>
    /// <remarks>
    /// HEARTBEAT
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.Heartbeat, Name="HEARTBEAT", Description=@"The heartbeat message shows that a system is present and responding. The type of the MAV and Autopilot hardware allow the receiving system to treat further messages from this system appropriate (e.g. by laying out the user interface based on the autopilot).")]
    public class HeartbeatMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Type of the MAV (quadrotor, helicopter, etc., up to 15 types, defined in MAV_TYPE ENUM)
        /// </summary>
        /// <remarks>
        /// type
        /// </remarks>
        private MavLink4Net.Messages.Common.Type _type;
        
        /// <summary>
        /// Autopilot type / class. defined in MAV_AUTOPILOT ENUM
        /// </summary>
        /// <remarks>
        /// autopilot
        /// </remarks>
        private MavLink4Net.Messages.Common.Autopilot _autopilot;
        
        /// <summary>
        /// System mode bitfield, see MAV_MODE_FLAG ENUM in mavlink/include/mavlink_types.h
        /// </summary>
        /// <remarks>
        /// base_mode
        /// </remarks>
        private MavLink4Net.Messages.Common.ModeFlag _baseMode;
        
        /// <summary>
        /// A bitfield for use for autopilot-specific flags.
        /// </summary>
        /// <remarks>
        /// custom_mode
        /// </remarks>
        private uint _customMode;
        
        /// <summary>
        /// System status flag, see MAV_STATE ENUM
        /// </summary>
        /// <remarks>
        /// system_status
        /// </remarks>
        private MavLink4Net.Messages.Common.State _systemStatus;
        
        /// <summary>
        /// MAVLink version, not writable by user, gets added by protocol because of magic data type: uint8_t_mavlink_version
        /// </summary>
        /// <remarks>
        /// mavlink_version
        /// </remarks>
        private byte _mavlinkVersion;
        
        public HeartbeatMessage() : 
                base(MavLink4Net.Messages.MavMessageType.Heartbeat)
        {
        }
        
        /// <summary>
        /// Type of the MAV (quadrotor, helicopter, etc., up to 15 types, defined in MAV_TYPE ENUM)
        /// </summary>
        [MessageFieldMetadata(Name="type", Type="MAV_TYPE enum", Description="Type of the MAV (quadrotor, helicopter, etc., up to 15 types, defined in MAV_TYPE" +
            " ENUM)")]
        public MavLink4Net.Messages.Common.Type Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        /// <summary>
        /// Autopilot type / class. defined in MAV_AUTOPILOT ENUM
        /// </summary>
        [MessageFieldMetadata(Name="autopilot", Type="MAV_AUTOPILOT enum", Description="Autopilot type / class. defined in MAV_AUTOPILOT ENUM")]
        public MavLink4Net.Messages.Common.Autopilot Autopilot
        {
            get
            {
                return this._autopilot;
            }
            set
            {
                this._autopilot = value;
            }
        }
        
        /// <summary>
        /// System mode bitfield, see MAV_MODE_FLAG ENUM in mavlink/include/mavlink_types.h
        /// </summary>
        [MessageFieldMetadata(Name="base_mode", Type="MAV_MODE_FLAG enum", Display="bitmask", Description="System mode bitfield, see MAV_MODE_FLAG ENUM in mavlink/include/mavlink_types.h")]
        public MavLink4Net.Messages.Common.ModeFlag BaseMode
        {
            get
            {
                return this._baseMode;
            }
            set
            {
                this._baseMode = value;
            }
        }
        
        /// <summary>
        /// A bitfield for use for autopilot-specific flags.
        /// </summary>
        [MessageFieldMetadata(Name="custom_mode", Type="uint32_t", Description="A bitfield for use for autopilot-specific flags.")]
        public uint CustomMode
        {
            get
            {
                return this._customMode;
            }
            set
            {
                this._customMode = value;
            }
        }
        
        /// <summary>
        /// System status flag, see MAV_STATE ENUM
        /// </summary>
        [MessageFieldMetadata(Name="system_status", Type="MAV_STATE enum", Description="System status flag, see MAV_STATE ENUM")]
        public MavLink4Net.Messages.Common.State SystemStatus
        {
            get
            {
                return this._systemStatus;
            }
            set
            {
                this._systemStatus = value;
            }
        }
        
        /// <summary>
        /// MAVLink version, not writable by user, gets added by protocol because of magic data type: uint8_t_mavlink_version
        /// </summary>
        [MessageFieldMetadata(Name="mavlink_version", Type="uint8_t_mavlink_version", Description="MAVLink version, not writable by user, gets added by protocol because of magic da" +
            "ta type: uint8_t_mavlink_version")]
        public byte MavlinkVersion
        {
            get
            {
                return this._mavlinkVersion;
            }
            set
            {
                this._mavlinkVersion = value;
            }
        }
    }
}
