//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Reply to LOG_REQUEST_LIST
    /// </summary>
    /// <remarks>
    /// LOG_ENTRY
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.LogEntry, Name="LOG_ENTRY", Description="Reply to LOG_REQUEST_LIST")]
    public class LogEntryMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Log id
        /// </summary>
        /// <remarks>
        /// id
        /// </remarks>
        private ushort _id;
        
        /// <summary>
        /// Total number of logs
        /// </summary>
        /// <remarks>
        /// num_logs
        /// </remarks>
        private ushort _numLogs;
        
        /// <summary>
        /// High log number
        /// </summary>
        /// <remarks>
        /// last_log_num
        /// </remarks>
        private ushort _lastLogNum;
        
        /// <summary>
        /// UTC timestamp of log in seconds since 1970, or 0 if not available
        /// </summary>
        /// <remarks>
        /// time_utc
        /// </remarks>
        private uint _timeUtc;
        
        /// <summary>
        /// Size of the log (may be approximate) in bytes
        /// </summary>
        /// <remarks>
        /// size
        /// </remarks>
        private uint _size;
        
        public LogEntryMessage() : 
                base(MavLink4Net.Messages.MavMessageType.LogEntry, 56)
        {
        }
        
        /// <summary>
        /// Log id
        /// </summary>
        [MessageFieldMetadata(Name="id", Type="uint16_t", Description="Log id")]
        public ushort Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        /// <summary>
        /// Total number of logs
        /// </summary>
        [MessageFieldMetadata(Name="num_logs", Type="uint16_t", Description="Total number of logs")]
        public ushort NumLogs
        {
            get
            {
                return this._numLogs;
            }
            set
            {
                this._numLogs = value;
            }
        }
        
        /// <summary>
        /// High log number
        /// </summary>
        [MessageFieldMetadata(Name="last_log_num", Type="uint16_t", Description="High log number")]
        public ushort LastLogNum
        {
            get
            {
                return this._lastLogNum;
            }
            set
            {
                this._lastLogNum = value;
            }
        }
        
        /// <summary>
        /// UTC timestamp of log in seconds since 1970, or 0 if not available
        /// </summary>
        [MessageFieldMetadata(Name="time_utc", Type="uint32_t", Units="s", Description="UTC timestamp of log in seconds since 1970, or 0 if not available")]
        public uint TimeUtc
        {
            get
            {
                return this._timeUtc;
            }
            set
            {
                this._timeUtc = value;
            }
        }
        
        /// <summary>
        /// Size of the log (may be approximate) in bytes
        /// </summary>
        [MessageFieldMetadata(Name="size", Type="uint32_t", Units="bytes", Description="Size of the log (may be approximate) in bytes")]
        public uint Size
        {
            get
            {
                return this._size;
            }
            set
            {
                this._size = value;
            }
        }
    }
}
