//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// MAVLINK_DATA_STREAM_TYPE
    /// </remarks>
    public enum MavlinkDataStreamType
    {
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_JPEG
        /// </remarks>
        [Description(null)]
        Jpeg,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_BMP
        /// </remarks>
        [Description(null)]
        Bmp,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_RAW8U
        /// </remarks>
        [Description(null)]
        Raw8u,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_RAW32U
        /// </remarks>
        [Description(null)]
        Raw32u,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_PGM
        /// </remarks>
        [Description(null)]
        Pgm,
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// MAVLINK_DATA_STREAM_IMG_PNG
        /// </remarks>
        [Description(null)]
        Png,
    }
}
