//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.
    /// </summary>
    /// <remarks>
    /// MISSION_CURRENT
    /// </remarks>
    public class MissionCurrentMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Sequence
        /// </summary>
        /// <remarks>
        /// seq
        /// </remarks>
        private ushort _seq;
        
        public MissionCurrentMessage() : 
                base(MavLink4Net.Messages.MavMessageType.MissionCurrent, 28)
        {
        }
        
        /// <summary>
        /// Sequence
        /// </summary>
        public ushort Seq
        {
            get
            {
                return this._seq;
            }
            set
            {
                this._seq = value;
            }
        }
    }
}
