//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Request the information of the mission item with the sequence number seq. The response of the system to this message should be a MISSION_ITEM message. https://mavlink.io/en/protocol/mission.html
    /// </summary>
    /// <remarks>
    /// MISSION_REQUEST
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.MissionRequest, Name="MISSION_REQUEST", Description="Request the information of the mission item with the sequence number seq. The res" +
        "ponse of the system to this message should be a MISSION_ITEM message. https://ma" +
        "vlink.io/en/protocol/mission.html")]
    public class MissionRequestMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// System ID
        /// </summary>
        /// <remarks>
        /// target_system
        /// </remarks>
        private byte _targetSystem;
        
        /// <summary>
        /// Component ID
        /// </summary>
        /// <remarks>
        /// target_component
        /// </remarks>
        private byte _targetComponent;
        
        /// <summary>
        /// Sequence
        /// </summary>
        /// <remarks>
        /// seq
        /// </remarks>
        private ushort _seq;
        
        public MissionRequestMessage() : 
                base(MavLink4Net.Messages.MavMessageType.MissionRequest)
        {
        }
        
        /// <summary>
        /// System ID
        /// </summary>
        [MessageFieldMetadata(Name="target_system", Type="uint8_t", Description="System ID")]
        public byte TargetSystem
        {
            get
            {
                return this._targetSystem;
            }
            set
            {
                this._targetSystem = value;
            }
        }
        
        /// <summary>
        /// Component ID
        /// </summary>
        [MessageFieldMetadata(Name="target_component", Type="uint8_t", Description="Component ID")]
        public byte TargetComponent
        {
            get
            {
                return this._targetComponent;
            }
            set
            {
                this._targetComponent = value;
            }
        }
        
        /// <summary>
        /// Sequence
        /// </summary>
        [MessageFieldMetadata(Name="seq", Type="uint16_t", Description="Sequence")]
        public ushort Seq
        {
            get
            {
                return this._seq;
            }
            set
            {
                this._seq = value;
            }
        }
    }
}
