//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// This message is sent to the MAV to write a partial list. If start index == end index, only one item will be transmitted / updated. If the start index is NOT 0 and above the current list size, this request should be REJECTED!
    /// </summary>
    /// <remarks>
    /// MISSION_WRITE_PARTIAL_LIST
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.MissionWritePartialList, Name="MISSION_WRITE_PARTIAL_LIST", Description="This message is sent to the MAV to write a partial list. If start index == end in" +
        "dex, only one item will be transmitted / updated. If the start index is NOT 0 an" +
        "d above the current list size, this request should be REJECTED!")]
    public class MissionWritePartialListMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// System ID
        /// </summary>
        /// <remarks>
        /// target_system
        /// </remarks>
        private byte _targetSystem;
        
        /// <summary>
        /// Component ID
        /// </summary>
        /// <remarks>
        /// target_component
        /// </remarks>
        private byte _targetComponent;
        
        /// <summary>
        /// Start index, 0 by default and smaller / equal to the largest index of the current onboard list.
        /// </summary>
        /// <remarks>
        /// start_index
        /// </remarks>
        private short _startIndex;
        
        /// <summary>
        /// End index, equal or greater than start index.
        /// </summary>
        /// <remarks>
        /// end_index
        /// </remarks>
        private short _endIndex;
        
        public MissionWritePartialListMessage() : 
                base(MavLink4Net.Messages.MavMessageType.MissionWritePartialList)
        {
        }
        
        /// <summary>
        /// System ID
        /// </summary>
        [MessageFieldMetadata(Name="target_system", Type="uint8_t", Description="System ID")]
        public byte TargetSystem
        {
            get
            {
                return this._targetSystem;
            }
            set
            {
                this._targetSystem = value;
            }
        }
        
        /// <summary>
        /// Component ID
        /// </summary>
        [MessageFieldMetadata(Name="target_component", Type="uint8_t", Description="Component ID")]
        public byte TargetComponent
        {
            get
            {
                return this._targetComponent;
            }
            set
            {
                this._targetComponent = value;
            }
        }
        
        /// <summary>
        /// Start index, 0 by default and smaller / equal to the largest index of the current onboard list.
        /// </summary>
        [MessageFieldMetadata(Name="start_index", Type="int16_t", Description="Start index, 0 by default and smaller / equal to the largest index of the current" +
            " onboard list.")]
        public short StartIndex
        {
            get
            {
                return this._startIndex;
            }
            set
            {
                this._startIndex = value;
            }
        }
        
        /// <summary>
        /// End index, equal or greater than start index.
        /// </summary>
        [MessageFieldMetadata(Name="end_index", Type="int16_t", Description="End index, equal or greater than start index.")]
        public short EndIndex
        {
            get
            {
                return this._endIndex;
            }
            set
            {
                this._endIndex = value;
            }
        }
    }
}
