//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Request a partial list of mission items from the system/component. https://mavlink.io/en/protocol/mission.html. If start and end index are the same, just send one waypoint.
    /// </summary>
    /// <remarks>
    /// MISSION_REQUEST_PARTIAL_LIST
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.MissionRequestPartialList, Name="MISSION_REQUEST_PARTIAL_LIST", Description="Request a partial list of mission items from the system/component. https://mavlin" +
        "k.io/en/protocol/mission.html. If start and end index are the same, just send on" +
        "e waypoint.")]
    public class MissionRequestPartialListMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// System ID
        /// </summary>
        /// <remarks>
        /// target_system
        /// </remarks>
        private byte _targetSystem;
        
        /// <summary>
        /// Component ID
        /// </summary>
        /// <remarks>
        /// target_component
        /// </remarks>
        private byte _targetComponent;
        
        /// <summary>
        /// Start index, 0 by default
        /// </summary>
        /// <remarks>
        /// start_index
        /// </remarks>
        private short _startIndex;
        
        /// <summary>
        /// End index, -1 by default (-1: send list to end). Else a valid index of the list
        /// </summary>
        /// <remarks>
        /// end_index
        /// </remarks>
        private short _endIndex;
        
        public MissionRequestPartialListMessage() : 
                base(MavLink4Net.Messages.MavMessageType.MissionRequestPartialList, 212)
        {
        }
        
        /// <summary>
        /// System ID
        /// </summary>
        [MessageFieldMetadata(Name="target_system", Type="uint8_t", Description="System ID")]
        public byte TargetSystem
        {
            get
            {
                return this._targetSystem;
            }
            set
            {
                this._targetSystem = value;
            }
        }
        
        /// <summary>
        /// Component ID
        /// </summary>
        [MessageFieldMetadata(Name="target_component", Type="uint8_t", Description="Component ID")]
        public byte TargetComponent
        {
            get
            {
                return this._targetComponent;
            }
            set
            {
                this._targetComponent = value;
            }
        }
        
        /// <summary>
        /// Start index, 0 by default
        /// </summary>
        [MessageFieldMetadata(Name="start_index", Type="int16_t", Description="Start index, 0 by default")]
        public short StartIndex
        {
            get
            {
                return this._startIndex;
            }
            set
            {
                this._startIndex = value;
            }
        }
        
        /// <summary>
        /// End index, -1 by default (-1: send list to end). Else a valid index of the list
        /// </summary>
        [MessageFieldMetadata(Name="end_index", Type="int16_t", Description="End index, -1 by default (-1: send list to end). Else a valid index of the list")]
        public short EndIndex
        {
            get
            {
                return this._endIndex;
            }
            set
            {
                this._endIndex = value;
            }
        }
    }
}
