//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// A certain mission item has been reached. The system will either hold this position (or circle on the orbit) or (if the autocontinue on the WP was set) continue to the next waypoint.
    /// </summary>
    /// <remarks>
    /// MISSION_ITEM_REACHED
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.MissionItemReached, Name="MISSION_ITEM_REACHED", Description="A certain mission item has been reached. The system will either hold this positio" +
        "n (or circle on the orbit) or (if the autocontinue on the WP was set) continue t" +
        "o the next waypoint.")]
    public class MissionItemReachedMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Sequence
        /// </summary>
        /// <remarks>
        /// seq
        /// </remarks>
        private ushort _seq;
        
        public MissionItemReachedMessage() : 
                base(MavLink4Net.Messages.MavMessageType.MissionItemReached, 11)
        {
        }
        
        /// <summary>
        /// Sequence
        /// </summary>
        [MessageFieldMetadata(Name="seq", Type="uint16_t", Description="Sequence")]
        public ushort Seq
        {
            get
            {
                return this._seq;
            }
            set
            {
                this._seq = value;
            }
        }
    }
}
