//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Result from a PARAM_EXT_SET message.
    /// </summary>
    /// <remarks>
    /// PARAM_ACK
    /// </remarks>
    public enum ParamAck
    {
        
        /// <summary>
        /// Parameter value ACCEPTED and SET
        /// </summary>
        /// <remarks>
        /// PARAM_ACK_ACCEPTED
        /// </remarks>
        [Description("Parameter value ACCEPTED and SET")]
        Accepted = 0,
        
        /// <summary>
        /// Parameter value UNKNOWN/UNSUPPORTED
        /// </summary>
        /// <remarks>
        /// PARAM_ACK_VALUE_UNSUPPORTED
        /// </remarks>
        [Description("Parameter value UNKNOWN/UNSUPPORTED")]
        ValueUnsupported = 1,
        
        /// <summary>
        /// Parameter failed to set
        /// </summary>
        /// <remarks>
        /// PARAM_ACK_FAILED
        /// </remarks>
        [Description("Parameter failed to set")]
        Failed = 2,
        
        /// <summary>
        /// Parameter value received but not yet validated or set. A subsequent PARAM_EXT_ACK will follow once operation is completed with the actual result. These are for parameters that may take longer to set. Instead of waiting for an ACK and potentially timing out, you will immediately receive this response to let you know it was received.
        /// </summary>
        /// <remarks>
        /// PARAM_ACK_IN_PROGRESS
        /// </remarks>
        [Description(@"Parameter value received but not yet validated or set. A subsequent PARAM_EXT_ACK will follow once operation is completed with the actual result. These are for parameters that may take longer to set. Instead of waiting for an ACK and potentially timing out, you will immediately receive this response to let you know it was received.")]
        InProgress = 3,
    }
}
