//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Power supply status flags (bitmask)
    /// </summary>
    /// <remarks>
    /// MAV_POWER_STATUS
    /// </remarks>
    public enum PowerStatus
    {
        
        /// <summary>
        /// main brick power supply valid
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_BRICK_VALID
        /// </remarks>
        [Description("main brick power supply valid")]
        BrickValid = 1,
        
        /// <summary>
        /// main servo power supply valid for FMU
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_SERVO_VALID
        /// </remarks>
        [Description("main servo power supply valid for FMU")]
        ServoValid = 2,
        
        /// <summary>
        /// USB power is connected
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_USB_CONNECTED
        /// </remarks>
        [Description("USB power is connected")]
        UsbConnected = 4,
        
        /// <summary>
        /// peripheral supply is in over-current state
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_PERIPH_OVERCURRENT
        /// </remarks>
        [Description("peripheral supply is in over-current state")]
        PeriphOvercurrent = 8,
        
        /// <summary>
        /// hi-power peripheral supply is in over-current state
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_PERIPH_HIPOWER_OVERCURRENT
        /// </remarks>
        [Description("hi-power peripheral supply is in over-current state")]
        PeriphHipowerOvercurrent = 16,
        
        /// <summary>
        /// Power status has changed since boot
        /// </summary>
        /// <remarks>
        /// MAV_POWER_STATUS_CHANGED
        /// </remarks>
        [Description("Power status has changed since boot")]
        Changed = 32,
    }
}
