//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Power supply status
    /// </summary>
    /// <remarks>
    /// POWER_STATUS
    /// </remarks>
    public class PowerStatusMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// 5V rail voltage in millivolts
        /// </summary>
        /// <remarks>
        /// Vcc
        /// </remarks>
        private ushort _vcc;
        
        /// <summary>
        /// servo rail voltage in millivolts
        /// </summary>
        /// <remarks>
        /// Vservo
        /// </remarks>
        private ushort _vservo;
        
        /// <summary>
        /// power supply status flags (see MAV_POWER_STATUS enum)
        /// </summary>
        /// <remarks>
        /// flags
        /// </remarks>
        private PowerStatus _flags;
        
        public PowerStatusMessage() : 
                base(MavLink4Net.Messages.MavMessageType.PowerStatus, 203)
        {
        }
        
        /// <summary>
        /// 5V rail voltage in millivolts
        /// </summary>
        public ushort Vcc
        {
            get
            {
                return this._vcc;
            }
            set
            {
                this._vcc = value;
            }
        }
        
        /// <summary>
        /// servo rail voltage in millivolts
        /// </summary>
        public ushort Vservo
        {
            get
            {
                return this._vservo;
            }
            set
            {
                this._vservo = value;
            }
        }
        
        /// <summary>
        /// power supply status flags (see MAV_POWER_STATUS enum)
        /// </summary>
        public PowerStatus Flags
        {
            get
            {
                return this._flags;
            }
            set
            {
                this._flags = value;
            }
        }
    }
}
