//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// The PPM values of the RC channels received. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. Individual receivers/transmitters might violate this specification.
    /// </summary>
    /// <remarks>
    /// RC_CHANNELS
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.RcChannels, Name="RC_CHANNELS", Description="The PPM values of the RC channels received. The standard PPM modulation is as fol" +
        "lows: 1000 microseconds: 0%, 2000 microseconds: 100%. Individual receivers/trans" +
        "mitters might violate this specification.")]
    public class RcChannelsMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Timestamp (milliseconds since system boot)
        /// </summary>
        /// <remarks>
        /// time_boot_ms
        /// </remarks>
        private uint _timeBootMs;
        
        /// <summary>
        /// Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
        /// </summary>
        /// <remarks>
        /// chancount
        /// </remarks>
        private byte _chancount;
        
        /// <summary>
        /// RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan1_raw
        /// </remarks>
        private ushort _chan1Raw;
        
        /// <summary>
        /// RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan2_raw
        /// </remarks>
        private ushort _chan2Raw;
        
        /// <summary>
        /// RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan3_raw
        /// </remarks>
        private ushort _chan3Raw;
        
        /// <summary>
        /// RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan4_raw
        /// </remarks>
        private ushort _chan4Raw;
        
        /// <summary>
        /// RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan5_raw
        /// </remarks>
        private ushort _chan5Raw;
        
        /// <summary>
        /// RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan6_raw
        /// </remarks>
        private ushort _chan6Raw;
        
        /// <summary>
        /// RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan7_raw
        /// </remarks>
        private ushort _chan7Raw;
        
        /// <summary>
        /// RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan8_raw
        /// </remarks>
        private ushort _chan8Raw;
        
        /// <summary>
        /// RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan9_raw
        /// </remarks>
        private ushort _chan9Raw;
        
        /// <summary>
        /// RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan10_raw
        /// </remarks>
        private ushort _chan10Raw;
        
        /// <summary>
        /// RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan11_raw
        /// </remarks>
        private ushort _chan11Raw;
        
        /// <summary>
        /// RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan12_raw
        /// </remarks>
        private ushort _chan12Raw;
        
        /// <summary>
        /// RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan13_raw
        /// </remarks>
        private ushort _chan13Raw;
        
        /// <summary>
        /// RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan14_raw
        /// </remarks>
        private ushort _chan14Raw;
        
        /// <summary>
        /// RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan15_raw
        /// </remarks>
        private ushort _chan15Raw;
        
        /// <summary>
        /// RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan16_raw
        /// </remarks>
        private ushort _chan16Raw;
        
        /// <summary>
        /// RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan17_raw
        /// </remarks>
        private ushort _chan17Raw;
        
        /// <summary>
        /// RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        /// <remarks>
        /// chan18_raw
        /// </remarks>
        private ushort _chan18Raw;
        
        /// <summary>
        /// Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
        /// </summary>
        /// <remarks>
        /// rssi
        /// </remarks>
        private byte _rssi;
        
        public RcChannelsMessage() : 
                base(MavLink4Net.Messages.MavMessageType.RcChannels, 118)
        {
        }
        
        /// <summary>
        /// Timestamp (milliseconds since system boot)
        /// </summary>
        [MessageFieldMetadata(Name="time_boot_ms", Type="uint32_t", Units="ms", Description="Timestamp (milliseconds since system boot)")]
        public uint TimeBootMs
        {
            get
            {
                return this._timeBootMs;
            }
            set
            {
                this._timeBootMs = value;
            }
        }
        
        /// <summary>
        /// Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.
        /// </summary>
        [MessageFieldMetadata(Name="chancount", Type="uint8_t", Description="Total number of RC channels being received. This can be larger than 18, indicatin" +
            "g that more channels are available but not given in this message. This value sho" +
            "uld be 0 when no RC channels are available.")]
        public byte Chancount
        {
            get
            {
                return this._chancount;
            }
            set
            {
                this._chancount = value;
            }
        }
        
        /// <summary>
        /// RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan1_raw", Type="uint16_t", Units="us", Description="RC channel 1 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan1Raw
        {
            get
            {
                return this._chan1Raw;
            }
            set
            {
                this._chan1Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan2_raw", Type="uint16_t", Units="us", Description="RC channel 2 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan2Raw
        {
            get
            {
                return this._chan2Raw;
            }
            set
            {
                this._chan2Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan3_raw", Type="uint16_t", Units="us", Description="RC channel 3 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan3Raw
        {
            get
            {
                return this._chan3Raw;
            }
            set
            {
                this._chan3Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan4_raw", Type="uint16_t", Units="us", Description="RC channel 4 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan4Raw
        {
            get
            {
                return this._chan4Raw;
            }
            set
            {
                this._chan4Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan5_raw", Type="uint16_t", Units="us", Description="RC channel 5 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan5Raw
        {
            get
            {
                return this._chan5Raw;
            }
            set
            {
                this._chan5Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan6_raw", Type="uint16_t", Units="us", Description="RC channel 6 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan6Raw
        {
            get
            {
                return this._chan6Raw;
            }
            set
            {
                this._chan6Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan7_raw", Type="uint16_t", Units="us", Description="RC channel 7 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan7Raw
        {
            get
            {
                return this._chan7Raw;
            }
            set
            {
                this._chan7Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan8_raw", Type="uint16_t", Units="us", Description="RC channel 8 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan8Raw
        {
            get
            {
                return this._chan8Raw;
            }
            set
            {
                this._chan8Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan9_raw", Type="uint16_t", Units="us", Description="RC channel 9 value, in microseconds. A value of UINT16_MAX implies the channel is" +
            " unused.")]
        public ushort Chan9Raw
        {
            get
            {
                return this._chan9Raw;
            }
            set
            {
                this._chan9Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan10_raw", Type="uint16_t", Units="us", Description="RC channel 10 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan10Raw
        {
            get
            {
                return this._chan10Raw;
            }
            set
            {
                this._chan10Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan11_raw", Type="uint16_t", Units="us", Description="RC channel 11 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan11Raw
        {
            get
            {
                return this._chan11Raw;
            }
            set
            {
                this._chan11Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan12_raw", Type="uint16_t", Units="us", Description="RC channel 12 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan12Raw
        {
            get
            {
                return this._chan12Raw;
            }
            set
            {
                this._chan12Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan13_raw", Type="uint16_t", Units="us", Description="RC channel 13 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan13Raw
        {
            get
            {
                return this._chan13Raw;
            }
            set
            {
                this._chan13Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan14_raw", Type="uint16_t", Units="us", Description="RC channel 14 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan14Raw
        {
            get
            {
                return this._chan14Raw;
            }
            set
            {
                this._chan14Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan15_raw", Type="uint16_t", Units="us", Description="RC channel 15 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan15Raw
        {
            get
            {
                return this._chan15Raw;
            }
            set
            {
                this._chan15Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan16_raw", Type="uint16_t", Units="us", Description="RC channel 16 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan16Raw
        {
            get
            {
                return this._chan16Raw;
            }
            set
            {
                this._chan16Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan17_raw", Type="uint16_t", Units="us", Description="RC channel 17 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan17Raw
        {
            get
            {
                return this._chan17Raw;
            }
            set
            {
                this._chan17Raw = value;
            }
        }
        
        /// <summary>
        /// RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel is unused.
        /// </summary>
        [MessageFieldMetadata(Name="chan18_raw", Type="uint16_t", Units="us", Description="RC channel 18 value, in microseconds. A value of UINT16_MAX implies the channel i" +
            "s unused.")]
        public ushort Chan18Raw
        {
            get
            {
                return this._chan18Raw;
            }
            set
            {
                this._chan18Raw = value;
            }
        }
        
        /// <summary>
        /// Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.
        /// </summary>
        [MessageFieldMetadata(Name="rssi", Type="uint8_t", Units="%", Description="Receive signal strength indicator, 0: 0%, 100: 100%, 255: invalid/unknown.")]
        public byte Rssi
        {
            get
            {
                return this._rssi;
            }
            set
            {
                this._rssi = value;
            }
        }
    }
}
