//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// RTK GPS baseline coordinate system, used for RTK corrections
    /// </summary>
    /// <remarks>
    /// RTK_BASELINE_COORDINATE_SYSTEM
    /// </remarks>
    public enum RtkBaselineCoordinateSystem
    {
        
        /// <summary>
        /// Earth-centered, Earth-fixed
        /// </summary>
        /// <remarks>
        /// RTK_BASELINE_COORDINATE_SYSTEM_ECEF
        /// </remarks>
        [Description("Earth-centered, Earth-fixed")]
        Ecef = 0,
        
        /// <summary>
        /// North, East, Down
        /// </summary>
        /// <remarks>
        /// RTK_BASELINE_COORDINATE_SYSTEM_NED
        /// </remarks>
        [Description("North, East, Down")]
        Ned = 1,
    }
}
