//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Control a serial port. This can be used for raw access to an onboard serial peripheral such as a GPS or telemetry radio. It is designed to make it possible to update the devices firmware via MAVLink messages or change the devices settings. A message with zero bytes can be used to change just the baudrate.
    /// </summary>
    /// <remarks>
    /// SERIAL_CONTROL
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.SerialControl, Name="SERIAL_CONTROL", Description=@"Control a serial port. This can be used for raw access to an onboard serial peripheral such as a GPS or telemetry radio. It is designed to make it possible to update the devices firmware via MAVLink messages or change the devices settings. A message with zero bytes can be used to change just the baudrate.")]
    public class SerialControlMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// See SERIAL_CONTROL_DEV enum
        /// </summary>
        /// <remarks>
        /// device
        /// </remarks>
        private SerialControlDev _device;
        
        /// <summary>
        /// See SERIAL_CONTROL_FLAG enum
        /// </summary>
        /// <remarks>
        /// flags
        /// </remarks>
        private SerialControlFlag _flags;
        
        /// <summary>
        /// Timeout for reply data in milliseconds
        /// </summary>
        /// <remarks>
        /// timeout
        /// </remarks>
        private ushort _timeout;
        
        /// <summary>
        /// Baudrate of transfer. Zero means no change.
        /// </summary>
        /// <remarks>
        /// baudrate
        /// </remarks>
        private uint _baudrate;
        
        /// <summary>
        /// how many bytes in this transfer
        /// </summary>
        /// <remarks>
        /// count
        /// </remarks>
        private byte _count;
        
        /// <summary>
        /// serial data
        /// </summary>
        /// <remarks>
        /// data
        /// </remarks>
        private byte[] _data = new byte[70];
        
        public SerialControlMessage() : 
                base(MavLink4Net.Messages.MavMessageType.SerialControl, 220)
        {
        }
        
        /// <summary>
        /// See SERIAL_CONTROL_DEV enum
        /// </summary>
        [MessageFieldMetadata(Name="device", Type="SERIAL_CONTROL_DEV enum", Description="See SERIAL_CONTROL_DEV enum")]
        public SerialControlDev Device
        {
            get
            {
                return this._device;
            }
            set
            {
                this._device = value;
            }
        }
        
        /// <summary>
        /// See SERIAL_CONTROL_FLAG enum
        /// </summary>
        [MessageFieldMetadata(Name="flags", Type="SERIAL_CONTROL_FLAG enum", Display="bitmask", Description="See SERIAL_CONTROL_FLAG enum")]
        public SerialControlFlag Flags
        {
            get
            {
                return this._flags;
            }
            set
            {
                this._flags = value;
            }
        }
        
        /// <summary>
        /// Timeout for reply data in milliseconds
        /// </summary>
        [MessageFieldMetadata(Name="timeout", Type="uint16_t", Units="ms", Description="Timeout for reply data in milliseconds")]
        public ushort Timeout
        {
            get
            {
                return this._timeout;
            }
            set
            {
                this._timeout = value;
            }
        }
        
        /// <summary>
        /// Baudrate of transfer. Zero means no change.
        /// </summary>
        [MessageFieldMetadata(Name="baudrate", Type="uint32_t", Units="bits/s", Description="Baudrate of transfer. Zero means no change.")]
        public uint Baudrate
        {
            get
            {
                return this._baudrate;
            }
            set
            {
                this._baudrate = value;
            }
        }
        
        /// <summary>
        /// how many bytes in this transfer
        /// </summary>
        [MessageFieldMetadata(Name="count", Type="uint8_t", Units="bytes", Description="how many bytes in this transfer")]
        public byte Count
        {
            get
            {
                return this._count;
            }
            set
            {
                this._count = value;
            }
        }
        
        /// <summary>
        /// serial data
        /// </summary>
        [MessageFieldMetadata(Name="data", Type="uint8_t[70]", Description="serial data")]
        public byte[] Data
        {
            get
            {
                return this._data;
            }
            set
            {
                this._data = value;
            }
        }
    }
}
