//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// SERIAL_CONTROL device types
    /// </summary>
    /// <remarks>
    /// SERIAL_CONTROL_DEV
    /// </remarks>
    public enum SerialControlDev
    {
        
        /// <summary>
        /// First telemetry port
        /// </summary>
        /// <remarks>
        /// SERIAL_CONTROL_DEV_TELEM1
        /// </remarks>
        [Description("First telemetry port")]
        Telem1 = 0,
        
        /// <summary>
        /// Second telemetry port
        /// </summary>
        /// <remarks>
        /// SERIAL_CONTROL_DEV_TELEM2
        /// </remarks>
        [Description("Second telemetry port")]
        Telem2 = 1,
        
        /// <summary>
        /// First GPS port
        /// </summary>
        /// <remarks>
        /// SERIAL_CONTROL_DEV_GPS1
        /// </remarks>
        [Description("First GPS port")]
        Gps1 = 2,
        
        /// <summary>
        /// Second GPS port
        /// </summary>
        /// <remarks>
        /// SERIAL_CONTROL_DEV_GPS2
        /// </remarks>
        [Description("Second GPS port")]
        Gps2 = 3,
        
        /// <summary>
        /// system shell
        /// </summary>
        /// <remarks>
        /// SERIAL_CONTROL_DEV_SHELL
        /// </remarks>
        [Description("system shell")]
        Shell = 10,
    }
}
