//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Status text message. These messages are printed in yellow in the COMM console of QGroundControl. WARNING: They consume quite some bandwidth, so use only for important status and error messages. If implemented wisely, these messages are buffered on the MCU and sent only at a limited rate (e.g. 10 Hz).
    /// </summary>
    /// <remarks>
    /// STATUSTEXT
    /// </remarks>
    public class StatustextMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
        /// </summary>
        /// <remarks>
        /// severity
        /// </remarks>
        private Severity _severity;
        
        /// <summary>
        /// Status text message, without null termination character
        /// </summary>
        /// <remarks>
        /// text
        /// </remarks>
        private char[] _text = new char[50];
        
        public StatustextMessage() : 
                base(MavLink4Net.Messages.MavMessageType.Statustext, 83)
        {
        }
        
        /// <summary>
        /// Severity of status. Relies on the definitions within RFC-5424. See enum MAV_SEVERITY.
        /// </summary>
        public Severity Severity
        {
            get
            {
                return this._severity;
            }
            set
            {
                this._severity = value;
            }
        }
        
        /// <summary>
        /// Status text message, without null termination character
        /// </summary>
        public char[] Text
        {
            get
            {
                return this._text;
            }
            set
            {
                this._text = value;
            }
        }
    }
}
