//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// These encode the sensors whose status is sent as part of the SYS_STATUS message.
    /// </summary>
    /// <remarks>
    /// MAV_SYS_STATUS_SENSOR
    /// </remarks>
    public enum SysStatusSensor
    {
        
        /// <summary>
        /// 0x01 3D gyro
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_GYRO
        /// </remarks>
        [Description("0x01 3D gyro")]
        Sensor3dGyro = 1,
        
        /// <summary>
        /// 0x02 3D accelerometer
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_ACCEL
        /// </remarks>
        [Description("0x02 3D accelerometer")]
        Sensor3dAccel = 2,
        
        /// <summary>
        /// 0x04 3D magnetometer
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_MAG
        /// </remarks>
        [Description("0x04 3D magnetometer")]
        Sensor3dMag = 4,
        
        /// <summary>
        /// 0x08 absolute pressure
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE
        /// </remarks>
        [Description("0x08 absolute pressure")]
        SensorAbsolutePressure = 8,
        
        /// <summary>
        /// 0x10 differential pressure
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_DIFFERENTIAL_PRESSURE
        /// </remarks>
        [Description("0x10 differential pressure")]
        SensorDifferentialPressure = 16,
        
        /// <summary>
        /// 0x20 GPS
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_GPS
        /// </remarks>
        [Description("0x20 GPS")]
        SensorGps = 32,
        
        /// <summary>
        /// 0x40 optical flow
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_OPTICAL_FLOW
        /// </remarks>
        [Description("0x40 optical flow")]
        SensorOpticalFlow = 64,
        
        /// <summary>
        /// 0x80 computer vision position
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_VISION_POSITION
        /// </remarks>
        [Description("0x80 computer vision position")]
        SensorVisionPosition = 128,
        
        /// <summary>
        /// 0x100 laser based position
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_LASER_POSITION
        /// </remarks>
        [Description("0x100 laser based position")]
        SensorLaserPosition = 256,
        
        /// <summary>
        /// 0x200 external ground truth (Vicon or Leica)
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_EXTERNAL_GROUND_TRUTH
        /// </remarks>
        [Description("0x200 external ground truth (Vicon or Leica)")]
        SensorExternalGroundTruth = 512,
        
        /// <summary>
        /// 0x400 3D angular rate control
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_ANGULAR_RATE_CONTROL
        /// </remarks>
        [Description("0x400 3D angular rate control")]
        SensorAngularRateControl = 1024,
        
        /// <summary>
        /// 0x800 attitude stabilization
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_ATTITUDE_STABILIZATION
        /// </remarks>
        [Description("0x800 attitude stabilization")]
        SensorAttitudeStabilization = 2048,
        
        /// <summary>
        /// 0x1000 yaw position
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_YAW_POSITION
        /// </remarks>
        [Description("0x1000 yaw position")]
        SensorYawPosition = 4096,
        
        /// <summary>
        /// 0x2000 z/altitude control
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_Z_ALTITUDE_CONTROL
        /// </remarks>
        [Description("0x2000 z/altitude control")]
        SensorZAltitudeControl = 8192,
        
        /// <summary>
        /// 0x4000 x/y position control
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_XY_POSITION_CONTROL
        /// </remarks>
        [Description("0x4000 x/y position control")]
        SensorXyPositionControl = 16384,
        
        /// <summary>
        /// 0x8000 motor outputs / control
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_MOTOR_OUTPUTS
        /// </remarks>
        [Description("0x8000 motor outputs / control")]
        SensorMotorOutputs = 32768,
        
        /// <summary>
        /// 0x10000 rc receiver
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_RC_RECEIVER
        /// </remarks>
        [Description("0x10000 rc receiver")]
        SensorRcReceiver = 65536,
        
        /// <summary>
        /// 0x20000 2nd 3D gyro
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_GYRO2
        /// </remarks>
        [Description("0x20000 2nd 3D gyro")]
        Sensor3dGyro2 = 131072,
        
        /// <summary>
        /// 0x40000 2nd 3D accelerometer
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_ACCEL2
        /// </remarks>
        [Description("0x40000 2nd 3D accelerometer")]
        Sensor3dAccel2 = 262144,
        
        /// <summary>
        /// 0x80000 2nd 3D magnetometer
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_3D_MAG2
        /// </remarks>
        [Description("0x80000 2nd 3D magnetometer")]
        Sensor3dMag2 = 524288,
        
        /// <summary>
        /// 0x100000 geofence
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_GEOFENCE
        /// </remarks>
        [Description("0x100000 geofence")]
        Geofence = 1048576,
        
        /// <summary>
        /// 0x200000 AHRS subsystem health
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_AHRS
        /// </remarks>
        [Description("0x200000 AHRS subsystem health")]
        Ahrs = 2097152,
        
        /// <summary>
        /// 0x400000 Terrain subsystem health
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_TERRAIN
        /// </remarks>
        [Description("0x400000 Terrain subsystem health")]
        Terrain = 4194304,
        
        /// <summary>
        /// 0x800000 Motors are reversed
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_REVERSE_MOTOR
        /// </remarks>
        [Description("0x800000 Motors are reversed")]
        ReverseMotor = 8388608,
        
        /// <summary>
        /// 0x1000000 Logging
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_LOGGING
        /// </remarks>
        [Description("0x1000000 Logging")]
        Logging = 16777216,
        
        /// <summary>
        /// 0x2000000 Battery
        /// </summary>
        /// <remarks>
        /// MAV_SYS_STATUS_SENSOR_BATTERY
        /// </remarks>
        [Description("0x2000000 Battery")]
        SensorBattery = 33554432,
    }
}
