//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Terrain data sent from GCS. The lat/lon and grid_spacing must be the same as a lat/lon from a TERRAIN_REQUEST
    /// </summary>
    /// <remarks>
    /// TERRAIN_DATA
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.TerrainData, Name="TERRAIN_DATA", Description="Terrain data sent from GCS. The lat/lon and grid_spacing must be the same as a la" +
        "t/lon from a TERRAIN_REQUEST")]
    public class TerrainDataMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Latitude of SW corner of first grid (degrees *10^7)
        /// </summary>
        /// <remarks>
        /// lat
        /// </remarks>
        private int _lat;
        
        /// <summary>
        /// Longitude of SW corner of first grid (in degrees *10^7)
        /// </summary>
        /// <remarks>
        /// lon
        /// </remarks>
        private int _lon;
        
        /// <summary>
        /// Grid spacing in meters
        /// </summary>
        /// <remarks>
        /// grid_spacing
        /// </remarks>
        private ushort _gridSpacing;
        
        /// <summary>
        /// bit within the terrain request mask
        /// </summary>
        /// <remarks>
        /// gridbit
        /// </remarks>
        private byte _gridbit;
        
        /// <summary>
        /// Terrain data in meters AMSL
        /// </summary>
        /// <remarks>
        /// data
        /// </remarks>
        private short[] _data = new short[16];
        
        public TerrainDataMessage() : 
                base(MavLink4Net.Messages.MavMessageType.TerrainData)
        {
        }
        
        /// <summary>
        /// Latitude of SW corner of first grid (degrees *10^7)
        /// </summary>
        [MessageFieldMetadata(Name="lat", Type="int32_t", Units="degE7", Description="Latitude of SW corner of first grid (degrees *10^7)")]
        public int Lat
        {
            get
            {
                return this._lat;
            }
            set
            {
                this._lat = value;
            }
        }
        
        /// <summary>
        /// Longitude of SW corner of first grid (in degrees *10^7)
        /// </summary>
        [MessageFieldMetadata(Name="lon", Type="int32_t", Units="degE7", Description="Longitude of SW corner of first grid (in degrees *10^7)")]
        public int Lon
        {
            get
            {
                return this._lon;
            }
            set
            {
                this._lon = value;
            }
        }
        
        /// <summary>
        /// Grid spacing in meters
        /// </summary>
        [MessageFieldMetadata(Name="grid_spacing", Type="uint16_t", Units="m", Description="Grid spacing in meters")]
        public ushort GridSpacing
        {
            get
            {
                return this._gridSpacing;
            }
            set
            {
                this._gridSpacing = value;
            }
        }
        
        /// <summary>
        /// bit within the terrain request mask
        /// </summary>
        [MessageFieldMetadata(Name="gridbit", Type="uint8_t", Description="bit within the terrain request mask")]
        public byte Gridbit
        {
            get
            {
                return this._gridbit;
            }
            set
            {
                this._gridbit = value;
            }
        }
        
        /// <summary>
        /// Terrain data in meters AMSL
        /// </summary>
        [MessageFieldMetadata(Name="data", Type="int16_t[16]", Units="m", Description="Terrain data in meters AMSL")]
        public short[] Data
        {
            get
            {
                return this._data;
            }
            set
            {
                this._data = value;
            }
        }
    }
}
