//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Response from a TERRAIN_CHECK request
    /// </summary>
    /// <remarks>
    /// TERRAIN_REPORT
    /// </remarks>
    public class TerrainReportMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Latitude (degrees *10^7)
        /// </summary>
        /// <remarks>
        /// lat
        /// </remarks>
        private int _lat;
        
        /// <summary>
        /// Longitude (degrees *10^7)
        /// </summary>
        /// <remarks>
        /// lon
        /// </remarks>
        private int _lon;
        
        /// <summary>
        /// grid spacing (zero if terrain at this location unavailable)
        /// </summary>
        /// <remarks>
        /// spacing
        /// </remarks>
        private ushort _spacing;
        
        /// <summary>
        /// Terrain height in meters AMSL
        /// </summary>
        /// <remarks>
        /// terrain_height
        /// </remarks>
        private float _terrainHeight;
        
        /// <summary>
        /// Current vehicle height above lat/lon terrain height (meters)
        /// </summary>
        /// <remarks>
        /// current_height
        /// </remarks>
        private float _currentHeight;
        
        /// <summary>
        /// Number of 4x4 terrain blocks waiting to be received or read from disk
        /// </summary>
        /// <remarks>
        /// pending
        /// </remarks>
        private ushort _pending;
        
        /// <summary>
        /// Number of 4x4 terrain blocks in memory
        /// </summary>
        /// <remarks>
        /// loaded
        /// </remarks>
        private ushort _loaded;
        
        public TerrainReportMessage() : 
                base(MavLink4Net.Messages.MavMessageType.TerrainReport, 1)
        {
        }
        
        /// <summary>
        /// Latitude (degrees *10^7)
        /// </summary>
        public int Lat
        {
            get
            {
                return this._lat;
            }
            set
            {
                this._lat = value;
            }
        }
        
        /// <summary>
        /// Longitude (degrees *10^7)
        /// </summary>
        public int Lon
        {
            get
            {
                return this._lon;
            }
            set
            {
                this._lon = value;
            }
        }
        
        /// <summary>
        /// grid spacing (zero if terrain at this location unavailable)
        /// </summary>
        public ushort Spacing
        {
            get
            {
                return this._spacing;
            }
            set
            {
                this._spacing = value;
            }
        }
        
        /// <summary>
        /// Terrain height in meters AMSL
        /// </summary>
        public float TerrainHeight
        {
            get
            {
                return this._terrainHeight;
            }
            set
            {
                this._terrainHeight = value;
            }
        }
        
        /// <summary>
        /// Current vehicle height above lat/lon terrain height (meters)
        /// </summary>
        public float CurrentHeight
        {
            get
            {
                return this._currentHeight;
            }
            set
            {
                this._currentHeight = value;
            }
        }
        
        /// <summary>
        /// Number of 4x4 terrain blocks waiting to be received or read from disk
        /// </summary>
        public ushort Pending
        {
            get
            {
                return this._pending;
            }
            set
            {
                this._pending = value;
            }
        }
        
        /// <summary>
        /// Number of 4x4 terrain blocks in memory
        /// </summary>
        public ushort Loaded
        {
            get
            {
                return this._loaded;
            }
            set
            {
                this._loaded = value;
            }
        }
    }
}
