//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Time synchronization message.
    /// </summary>
    /// <remarks>
    /// TIMESYNC
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.Timesync, Name="TIMESYNC", Description="Time synchronization message.")]
    public class TimesyncMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Time sync timestamp 1
        /// </summary>
        /// <remarks>
        /// tc1
        /// </remarks>
        private long _tc1;
        
        /// <summary>
        /// Time sync timestamp 2
        /// </summary>
        /// <remarks>
        /// ts1
        /// </remarks>
        private long _ts1;
        
        public TimesyncMessage() : 
                base(MavLink4Net.Messages.MavMessageType.Timesync, 34)
        {
        }
        
        /// <summary>
        /// Time sync timestamp 1
        /// </summary>
        [MessageFieldMetadata(Name="tc1", Type="int64_t", Description="Time sync timestamp 1")]
        public long Tc1
        {
            get
            {
                return this._tc1;
            }
            set
            {
                this._tc1 = value;
            }
        }
        
        /// <summary>
        /// Time sync timestamp 2
        /// </summary>
        [MessageFieldMetadata(Name="ts1", Type="int64_t", Description="Time sync timestamp 2")]
        public long Ts1
        {
            get
            {
                return this._ts1;
            }
            set
            {
                this._ts1 = value;
            }
        }
    }
}
