//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using MavLink4Net.Messages.Metadata;
using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Metrics typically displayed on a HUD for fixed wing aircraft
    /// </summary>
    /// <remarks>
    /// VFR_HUD
    /// </remarks>
    [MessageMetadata(Type=MavLink4Net.Messages.MavMessageType.VfrHud, Name="VFR_HUD", Description="Metrics typically displayed on a HUD for fixed wing aircraft")]
    public class VfrHudMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Current airspeed in m/s
        /// </summary>
        /// <remarks>
        /// airspeed
        /// </remarks>
        private float _airspeed;
        
        /// <summary>
        /// Current ground speed in m/s
        /// </summary>
        /// <remarks>
        /// groundspeed
        /// </remarks>
        private float _groundspeed;
        
        /// <summary>
        /// Current heading in degrees, in compass units (0..360, 0=north)
        /// </summary>
        /// <remarks>
        /// heading
        /// </remarks>
        private short _heading;
        
        /// <summary>
        /// Current throttle setting in integer percent, 0 to 100
        /// </summary>
        /// <remarks>
        /// throttle
        /// </remarks>
        private ushort _throttle;
        
        /// <summary>
        /// Current altitude (MSL), in meters
        /// </summary>
        /// <remarks>
        /// alt
        /// </remarks>
        private float _alt;
        
        /// <summary>
        /// Current climb rate in meters/second
        /// </summary>
        /// <remarks>
        /// climb
        /// </remarks>
        private float _climb;
        
        public VfrHudMessage() : 
                base(MavLink4Net.Messages.MavMessageType.VfrHud)
        {
        }
        
        /// <summary>
        /// Current airspeed in m/s
        /// </summary>
        [MessageFieldMetadata(Name="airspeed", Type="float", Units="m/s", Description="Current airspeed in m/s")]
        public float Airspeed
        {
            get
            {
                return this._airspeed;
            }
            set
            {
                this._airspeed = value;
            }
        }
        
        /// <summary>
        /// Current ground speed in m/s
        /// </summary>
        [MessageFieldMetadata(Name="groundspeed", Type="float", Units="m/s", Description="Current ground speed in m/s")]
        public float Groundspeed
        {
            get
            {
                return this._groundspeed;
            }
            set
            {
                this._groundspeed = value;
            }
        }
        
        /// <summary>
        /// Current heading in degrees, in compass units (0..360, 0=north)
        /// </summary>
        [MessageFieldMetadata(Name="heading", Type="int16_t", Units="deg", Description="Current heading in degrees, in compass units (0..360, 0=north)")]
        public short Heading
        {
            get
            {
                return this._heading;
            }
            set
            {
                this._heading = value;
            }
        }
        
        /// <summary>
        /// Current throttle setting in integer percent, 0 to 100
        /// </summary>
        [MessageFieldMetadata(Name="throttle", Type="uint16_t", Units="%", Description="Current throttle setting in integer percent, 0 to 100")]
        public ushort Throttle
        {
            get
            {
                return this._throttle;
            }
            set
            {
                this._throttle = value;
            }
        }
        
        /// <summary>
        /// Current altitude (MSL), in meters
        /// </summary>
        [MessageFieldMetadata(Name="alt", Type="float", Units="m", Description="Current altitude (MSL), in meters")]
        public float Alt
        {
            get
            {
                return this._alt;
            }
            set
            {
                this._alt = value;
            }
        }
        
        /// <summary>
        /// Current climb rate in meters/second
        /// </summary>
        [MessageFieldMetadata(Name="climb", Type="float", Units="m/s", Description="Current climb rate in meters/second")]
        public float Climb
        {
            get
            {
                return this._climb;
            }
            set
            {
                this._climb = value;
            }
        }
    }
}
