//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Vibration levels and accelerometer clipping
    /// </summary>
    /// <remarks>
    /// VIBRATION
    /// </remarks>
    public class VibrationMessage : MavLink4Net.Messages.Message
    {
        
        /// <summary>
        /// Timestamp (micros since boot or Unix epoch)
        /// </summary>
        /// <remarks>
        /// time_usec
        /// </remarks>
        private ulong _timeUsec;
        
        /// <summary>
        /// Vibration levels on X-axis
        /// </summary>
        /// <remarks>
        /// vibration_x
        /// </remarks>
        private float _vibrationX;
        
        /// <summary>
        /// Vibration levels on Y-axis
        /// </summary>
        /// <remarks>
        /// vibration_y
        /// </remarks>
        private float _vibrationY;
        
        /// <summary>
        /// Vibration levels on Z-axis
        /// </summary>
        /// <remarks>
        /// vibration_z
        /// </remarks>
        private float _vibrationZ;
        
        /// <summary>
        /// first accelerometer clipping count
        /// </summary>
        /// <remarks>
        /// clipping_0
        /// </remarks>
        private uint _clipping0;
        
        /// <summary>
        /// second accelerometer clipping count
        /// </summary>
        /// <remarks>
        /// clipping_1
        /// </remarks>
        private uint _clipping1;
        
        /// <summary>
        /// third accelerometer clipping count
        /// </summary>
        /// <remarks>
        /// clipping_2
        /// </remarks>
        private uint _clipping2;
        
        public VibrationMessage() : 
                base(MavLink4Net.Messages.MavMessageType.Vibration, 90)
        {
        }
        
        /// <summary>
        /// Timestamp (micros since boot or Unix epoch)
        /// </summary>
        public ulong TimeUsec
        {
            get
            {
                return this._timeUsec;
            }
            set
            {
                this._timeUsec = value;
            }
        }
        
        /// <summary>
        /// Vibration levels on X-axis
        /// </summary>
        public float VibrationX
        {
            get
            {
                return this._vibrationX;
            }
            set
            {
                this._vibrationX = value;
            }
        }
        
        /// <summary>
        /// Vibration levels on Y-axis
        /// </summary>
        public float VibrationY
        {
            get
            {
                return this._vibrationY;
            }
            set
            {
                this._vibrationY = value;
            }
        }
        
        /// <summary>
        /// Vibration levels on Z-axis
        /// </summary>
        public float VibrationZ
        {
            get
            {
                return this._vibrationZ;
            }
            set
            {
                this._vibrationZ = value;
            }
        }
        
        /// <summary>
        /// first accelerometer clipping count
        /// </summary>
        public uint Clipping0
        {
            get
            {
                return this._clipping0;
            }
            set
            {
                this._clipping0 = value;
            }
        }
        
        /// <summary>
        /// second accelerometer clipping count
        /// </summary>
        public uint Clipping1
        {
            get
            {
                return this._clipping1;
            }
            set
            {
                this._clipping1 = value;
            }
        }
        
        /// <summary>
        /// third accelerometer clipping count
        /// </summary>
        public uint Clipping2
        {
            get
            {
                return this._clipping2;
            }
            set
            {
                this._clipping2 = value;
            }
        }
    }
}
