//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Common
{
    
    
    /// <summary>
    /// Enumeration of VTOL states
    /// </summary>
    /// <remarks>
    /// MAV_VTOL_STATE
    /// </remarks>
    public enum VtolState
    {
        
        /// <summary>
        /// MAV is not configured as VTOL
        /// </summary>
        /// <remarks>
        /// MAV_VTOL_STATE_UNDEFINED
        /// </remarks>
        [Description("MAV is not configured as VTOL")]
        Undefined = 0,
        
        /// <summary>
        /// VTOL is in transition from multicopter to fixed-wing
        /// </summary>
        /// <remarks>
        /// MAV_VTOL_STATE_TRANSITION_TO_FW
        /// </remarks>
        [Description("VTOL is in transition from multicopter to fixed-wing")]
        TransitionToFw = 1,
        
        /// <summary>
        /// VTOL is in transition from fixed-wing to multicopter
        /// </summary>
        /// <remarks>
        /// MAV_VTOL_STATE_TRANSITION_TO_MC
        /// </remarks>
        [Description("VTOL is in transition from fixed-wing to multicopter")]
        TransitionToMc = 2,
        
        /// <summary>
        /// VTOL is in multicopter state
        /// </summary>
        /// <remarks>
        /// MAV_VTOL_STATE_MC
        /// </remarks>
        [Description("VTOL is in multicopter state")]
        Mc = 3,
        
        /// <summary>
        /// VTOL is in fixed-wing state
        /// </summary>
        /// <remarks>
        /// MAV_VTOL_STATE_FW
        /// </remarks>
        [Description("VTOL is in fixed-wing state")]
        Fw = 4,
    }
}
