//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class AttPosMocapMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.AttPosMocapMessage tMessage = message as MavLink4Net.Messages.Common.AttPosMocapMessage;
            writer.Write(tMessage.TimeUsec);
            writer.Write(tMessage.Q[0]);
            writer.Write(tMessage.Q[1]);
            writer.Write(tMessage.Q[2]);
            writer.Write(tMessage.Q[3]);
            writer.Write(tMessage.X);
            writer.Write(tMessage.Y);
            writer.Write(tMessage.Z);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.AttPosMocapMessage message = new MavLink4Net.Messages.Common.AttPosMocapMessage();
            message.TimeUsec = reader.ReadUInt64();
            message.Q[0] = reader.ReadSingle();
            message.Q[1] = reader.ReadSingle();
            message.Q[2] = reader.ReadSingle();
            message.Q[3] = reader.ReadSingle();
            message.X = reader.ReadSingle();
            message.Y = reader.ReadSingle();
            message.Z = reader.ReadSingle();
            return message;
        }
    }
}
