//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class HilRcInputsRawMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.HilRcInputsRawMessage tMessage = message as MavLink4Net.Messages.Common.HilRcInputsRawMessage;
            writer.Write(tMessage.TimeUsec);
            writer.Write(tMessage.Chan1Raw);
            writer.Write(tMessage.Chan2Raw);
            writer.Write(tMessage.Chan3Raw);
            writer.Write(tMessage.Chan4Raw);
            writer.Write(tMessage.Chan5Raw);
            writer.Write(tMessage.Chan6Raw);
            writer.Write(tMessage.Chan7Raw);
            writer.Write(tMessage.Chan8Raw);
            writer.Write(tMessage.Chan9Raw);
            writer.Write(tMessage.Chan10Raw);
            writer.Write(tMessage.Chan11Raw);
            writer.Write(tMessage.Chan12Raw);
            writer.Write(tMessage.Rssi);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.HilRcInputsRawMessage message = new MavLink4Net.Messages.Common.HilRcInputsRawMessage();
            message.TimeUsec = reader.ReadUInt64();
            message.Chan1Raw = reader.ReadUInt16();
            message.Chan2Raw = reader.ReadUInt16();
            message.Chan3Raw = reader.ReadUInt16();
            message.Chan4Raw = reader.ReadUInt16();
            message.Chan5Raw = reader.ReadUInt16();
            message.Chan6Raw = reader.ReadUInt16();
            message.Chan7Raw = reader.ReadUInt16();
            message.Chan8Raw = reader.ReadUInt16();
            message.Chan9Raw = reader.ReadUInt16();
            message.Chan10Raw = reader.ReadUInt16();
            message.Chan11Raw = reader.ReadUInt16();
            message.Chan12Raw = reader.ReadUInt16();
            message.Rssi = reader.ReadByte();
            return message;
        }
    }
}
