//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class LandingTargetMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.Message message)
        {
            MavLink4Net.Messages.Common.LandingTargetMessage tMessage = message as MavLink4Net.Messages.Common.LandingTargetMessage;
            writer.Write(tMessage.TimeUsec);
            writer.Write(tMessage.AngleX);
            writer.Write(tMessage.AngleY);
            writer.Write(tMessage.Distance);
            writer.Write(tMessage.SizeX);
            writer.Write(tMessage.SizeY);
            writer.Write(tMessage.X);
            writer.Write(tMessage.Y);
            writer.Write(tMessage.Z);
            writer.Write(tMessage.Q[0]);
            writer.Write(tMessage.Q[1]);
            writer.Write(tMessage.Q[2]);
            writer.Write(tMessage.Q[3]);
            writer.Write(tMessage.TargetNum);
            writer.Write(((byte)(tMessage.Frame)));
            writer.Write(((byte)(tMessage.Type)));
            writer.Write(tMessage.PositionValid);
        }
        
        public MavLink4Net.Messages.Message Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.LandingTargetMessage message = new MavLink4Net.Messages.Common.LandingTargetMessage();
            message.TimeUsec = reader.ReadUInt64();
            message.AngleX = reader.ReadSingle();
            message.AngleY = reader.ReadSingle();
            message.Distance = reader.ReadSingle();
            message.SizeX = reader.ReadSingle();
            message.SizeY = reader.ReadSingle();
            message.X = reader.ReadSingle();
            message.Y = reader.ReadSingle();
            message.Z = reader.ReadSingle();
            message.Q[0] = reader.ReadSingle();
            message.Q[1] = reader.ReadSingle();
            message.Q[2] = reader.ReadSingle();
            message.Q[3] = reader.ReadSingle();
            message.TargetNum = reader.ReadByte();
            message.Frame = ((MavLink4Net.Messages.Common.Frame)(reader.ReadByte()));
            message.Type = ((MavLink4Net.Messages.Common.LandingTargetType)(reader.ReadByte()));
            message.PositionValid = reader.ReadByte();
            return message;
        }
    }
}
