//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class MemoryVectMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.MemoryVectMessage tMessage = message as MavLink4Net.Messages.Common.MemoryVectMessage;
            writer.Write(tMessage.Address);
            writer.Write(tMessage.Ver);
            writer.Write(tMessage.Type);
            writer.Write(tMessage.Value[0]);
            writer.Write(tMessage.Value[1]);
            writer.Write(tMessage.Value[2]);
            writer.Write(tMessage.Value[3]);
            writer.Write(tMessage.Value[4]);
            writer.Write(tMessage.Value[5]);
            writer.Write(tMessage.Value[6]);
            writer.Write(tMessage.Value[7]);
            writer.Write(tMessage.Value[8]);
            writer.Write(tMessage.Value[9]);
            writer.Write(tMessage.Value[10]);
            writer.Write(tMessage.Value[11]);
            writer.Write(tMessage.Value[12]);
            writer.Write(tMessage.Value[13]);
            writer.Write(tMessage.Value[14]);
            writer.Write(tMessage.Value[15]);
            writer.Write(tMessage.Value[16]);
            writer.Write(tMessage.Value[17]);
            writer.Write(tMessage.Value[18]);
            writer.Write(tMessage.Value[19]);
            writer.Write(tMessage.Value[20]);
            writer.Write(tMessage.Value[21]);
            writer.Write(tMessage.Value[22]);
            writer.Write(tMessage.Value[23]);
            writer.Write(tMessage.Value[24]);
            writer.Write(tMessage.Value[25]);
            writer.Write(tMessage.Value[26]);
            writer.Write(tMessage.Value[27]);
            writer.Write(tMessage.Value[28]);
            writer.Write(tMessage.Value[29]);
            writer.Write(tMessage.Value[30]);
            writer.Write(tMessage.Value[31]);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.MemoryVectMessage message = new MavLink4Net.Messages.Common.MemoryVectMessage();
            message.Address = reader.ReadUInt16();
            message.Ver = reader.ReadByte();
            message.Type = reader.ReadByte();
            message.Value[0] = reader.ReadSByte();
            message.Value[1] = reader.ReadSByte();
            message.Value[2] = reader.ReadSByte();
            message.Value[3] = reader.ReadSByte();
            message.Value[4] = reader.ReadSByte();
            message.Value[5] = reader.ReadSByte();
            message.Value[6] = reader.ReadSByte();
            message.Value[7] = reader.ReadSByte();
            message.Value[8] = reader.ReadSByte();
            message.Value[9] = reader.ReadSByte();
            message.Value[10] = reader.ReadSByte();
            message.Value[11] = reader.ReadSByte();
            message.Value[12] = reader.ReadSByte();
            message.Value[13] = reader.ReadSByte();
            message.Value[14] = reader.ReadSByte();
            message.Value[15] = reader.ReadSByte();
            message.Value[16] = reader.ReadSByte();
            message.Value[17] = reader.ReadSByte();
            message.Value[18] = reader.ReadSByte();
            message.Value[19] = reader.ReadSByte();
            message.Value[20] = reader.ReadSByte();
            message.Value[21] = reader.ReadSByte();
            message.Value[22] = reader.ReadSByte();
            message.Value[23] = reader.ReadSByte();
            message.Value[24] = reader.ReadSByte();
            message.Value[25] = reader.ReadSByte();
            message.Value[26] = reader.ReadSByte();
            message.Value[27] = reader.ReadSByte();
            message.Value[28] = reader.ReadSByte();
            message.Value[29] = reader.ReadSByte();
            message.Value[30] = reader.ReadSByte();
            message.Value[31] = reader.ReadSByte();
            return message;
        }
    }
}
