//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class MessageIntervalMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.MessageIntervalMessage tMessage = message as MavLink4Net.Messages.Common.MessageIntervalMessage;
            writer.Write(tMessage.IntervalUs);
            writer.Write(tMessage.MessageId);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.MessageIntervalMessage message = new MavLink4Net.Messages.Common.MessageIntervalMessage();
            message.IntervalUs = reader.ReadInt32();
            message.MessageId = reader.ReadUInt16();
            return message;
        }
    }
}
