//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class MissionItemMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.Message message)
        {
            MavLink4Net.Messages.Common.MissionItemMessage tMessage = message as MavLink4Net.Messages.Common.MissionItemMessage;
            writer.Write(tMessage.Param1);
            writer.Write(tMessage.Param2);
            writer.Write(tMessage.Param3);
            writer.Write(tMessage.Param4);
            writer.Write(tMessage.X);
            writer.Write(tMessage.Y);
            writer.Write(tMessage.Z);
            writer.Write(tMessage.Seq);
            writer.Write(((ushort)(tMessage.Command)));
            writer.Write(tMessage.TargetSystem);
            writer.Write(tMessage.TargetComponent);
            writer.Write(((byte)(tMessage.Frame)));
            writer.Write(tMessage.Current);
            writer.Write(tMessage.Autocontinue);
            writer.Write(((byte)(tMessage.MissionType)));
        }
        
        public MavLink4Net.Messages.Message Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.MissionItemMessage message = new MavLink4Net.Messages.Common.MissionItemMessage();
            message.Param1 = reader.ReadSingle();
            message.Param2 = reader.ReadSingle();
            message.Param3 = reader.ReadSingle();
            message.Param4 = reader.ReadSingle();
            message.X = reader.ReadSingle();
            message.Y = reader.ReadSingle();
            message.Z = reader.ReadSingle();
            message.Seq = reader.ReadUInt16();
            message.Command = ((MavLink4Net.Messages.Common.Cmd)(reader.ReadUInt16()));
            message.TargetSystem = reader.ReadByte();
            message.TargetComponent = reader.ReadByte();
            message.Frame = ((MavLink4Net.Messages.Common.Frame)(reader.ReadByte()));
            message.Current = reader.ReadByte();
            message.Autocontinue = reader.ReadByte();
            message.MissionType = ((MavLink4Net.Messages.Common.MissionType)(reader.ReadByte()));
            return message;
        }
    }
}
