//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class RcChannelsOverrideMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.RcChannelsOverrideMessage tMessage = message as MavLink4Net.Messages.Common.RcChannelsOverrideMessage;
            writer.Write(tMessage.Chan1Raw);
            writer.Write(tMessage.Chan2Raw);
            writer.Write(tMessage.Chan3Raw);
            writer.Write(tMessage.Chan4Raw);
            writer.Write(tMessage.Chan5Raw);
            writer.Write(tMessage.Chan6Raw);
            writer.Write(tMessage.Chan7Raw);
            writer.Write(tMessage.Chan8Raw);
            writer.Write(tMessage.TargetSystem);
            writer.Write(tMessage.TargetComponent);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.RcChannelsOverrideMessage message = new MavLink4Net.Messages.Common.RcChannelsOverrideMessage();
            message.Chan1Raw = reader.ReadUInt16();
            message.Chan2Raw = reader.ReadUInt16();
            message.Chan3Raw = reader.ReadUInt16();
            message.Chan4Raw = reader.ReadUInt16();
            message.Chan5Raw = reader.ReadUInt16();
            message.Chan6Raw = reader.ReadUInt16();
            message.Chan7Raw = reader.ReadUInt16();
            message.Chan8Raw = reader.ReadUInt16();
            message.TargetSystem = reader.ReadByte();
            message.TargetComponent = reader.ReadByte();
            return message;
        }
    }
}
