//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class TerrainCheckMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.Message message)
        {
            MavLink4Net.Messages.Common.TerrainCheckMessage tMessage = message as MavLink4Net.Messages.Common.TerrainCheckMessage;
            writer.Write(tMessage.Lat);
            writer.Write(tMessage.Lon);
        }
        
        public MavLink4Net.Messages.Message Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.TerrainCheckMessage message = new MavLink4Net.Messages.Common.TerrainCheckMessage();
            message.Lat = reader.ReadInt32();
            message.Lon = reader.ReadInt32();
            return message;
        }
    }
}
