//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace MavLink4Net.Messages.Serialization.Common
{
    
    
    public class TerrainReportMessageSerializer : MavLink4Net.Messages.Serialization.IMessageSerializer
    {
        
        public void Serialize(System.IO.BinaryWriter writer, MavLink4Net.Messages.IMessage message)
        {
            MavLink4Net.Messages.Common.TerrainReportMessage tMessage = message as MavLink4Net.Messages.Common.TerrainReportMessage;
            writer.Write(tMessage.Lat);
            writer.Write(tMessage.Lon);
            writer.Write(tMessage.TerrainHeight);
            writer.Write(tMessage.CurrentHeight);
            writer.Write(tMessage.Spacing);
            writer.Write(tMessage.Pending);
            writer.Write(tMessage.Loaded);
        }
        
        public MavLink4Net.Messages.IMessage Deserialize(System.IO.BinaryReader reader)
        {
            MavLink4Net.Messages.Common.TerrainReportMessage message = new MavLink4Net.Messages.Common.TerrainReportMessage();
            message.Lat = reader.ReadInt32();
            message.Lon = reader.ReadInt32();
            message.TerrainHeight = reader.ReadSingle();
            message.CurrentHeight = reader.ReadSingle();
            message.Spacing = reader.ReadUInt16();
            message.Pending = reader.ReadUInt16();
            message.Loaded = reader.ReadUInt16();
            return message;
        }
    }
}
